apiVersion: v2
name: domain-exporter
description: A Helm chart for Domain Expiry Prometheus Exporter
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - prometheus
  - exporter
  - domain
  - monitoring
home: https://github.com/kevin197011/domain-exporter
sources:
  - https://github.com/kevin197011/domain-exporter
maintainers:
  - name: kevin197011
    email: kevin197011@example.com